<a href="https://colab.research.google.com/github/crislanecas/estudos_python/blob/main/Ada%26SantanderCoders/01_Aula_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Lista

Agrupam mais de um caracter, numero ou até outras listas, dicionários e tuplas tudo na mesma lista.

In [ ]:
# Cria uma lista
lista = [1, 2, 3, 4, 5, 6]
print(lista)
print(type(lista))

[1, 2, 3, 4, 5, 6]
<class 'list'>


# Array

Assim como na lista os elementos podem ser editáveis, mas diferente da lista ele tem apenas um tipo de dado.

## array()

In [ ]:
# Cria um array com a lista
array = np.array(lista)
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## zeros()

In [ ]:
# Cria um array com elementos iguais a 0, utilizando método np.zero()
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Atribui um novo valor ao elemento da array
array[0] = 10
print(array)

[10  2  3  4  5  6]


# Matriz

É um array que tem mais de uma dimensão.

In [ ]:
# Cria uma matriz
matriz_zeros = np.zeros((5, 3)) # Defini o número de linhas e colunas respectivamente
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Calculos com array

In [ ]:
# Cria uma lista com notas
lista_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
array_notas = np.array(lista_notas)

In [ ]:
print('Máximo:', array_notas.max())
print('Mínimo:', array_notas.min())
print('Média:', array_notas.mean())
print('Desvio Padrão:', array_notas.std())
print('Posição menor:', array_notas.argmin())
print('Posição maior:', array_notas.argmax())

Máximo: 9.8
Mínimo: 5.6
Média: 7.76
Desvio Padrão: 1.5628179676469045
Posição menor: 1
Posição maior: 0


## Exercício



Questão 1

Você deseja criar um numpy array com 10 espaços, e depois preenchê-los com 10 valores para poder calcular o desvio padrão usando o método do numpy.

In [ ]:
# Cria um array com 10 espaços zerados
array_10 = np.zeros(10)

# Utiliza o for para preencher o array
for i in range(10):
    array_10[i] = i + 1

print(array_10)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Questão 2

Juliana está corrigindo provas de seus alunos e para isso salva as notas em uma lista.

Além de calcular a média da turma, Juliana também precisa determinar de forma rápida quem está acima e abaixo da média do colégio, e, para fazer isso de forma rápida, decidiu criar um array para auxiliá-la.

A partir da lista de notas, como Juliana pode criar esse array?

In [ ]:
lista_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
array_notas = np.array(lista_notas)

# Máscara Booleana

É uma maneira de indexar objetos no numpy, que funciona de maneira similar a um filtro, que pode ser simples ou composto

In [ ]:
# Cria uma array
covid_positivo = np.array(['yes', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'no'])

In [ ]:
# Cria uma lista validando os elementos
selecao = covid_positivo == 'yes'
selecao

array([ True, False, False,  True, False,  True,  True, False])

In [ ]:
# Altera os elementos conforme seleção criada acima
covid_positivo [selecao] = 'C19'
covid_positivo

array(['C19', 'no', 'no', 'C19', 'no', 'C19', 'C19', 'no'], dtype='<U3')

## Exercício

Em uma escola, a média para aprovação é 7. As notas dos alunos estão armazenadas em um array chamado 'notas'.

Escolha a expressão que pega 'notas' e salva em 'aprovados' um outro array booleano, com valor true apenas para as pessoas que passaram de ano:

In [ ]:
notas = np.array([9.8, 5.6, 7.8, 9.1, 6.5])
aprovados = notas >= 7
notas[aprovados]

array([9.8, 7.8, 9.1])